---
driver_config:
  name: ec2
  availability_zone: us-east-1d
  subnet_id: <%= ENV['EC2_SUBNET_ID'] %>
  security_group_ids: [<%= ENV['EC2_SECURITY_GROUP_ID'] %>]
  aws_ssh_key_id: <%= ENV['EC2_SSH_KEY_ID'] %>
  associate_public_ip: true
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  iam_profile_name: <%= ENV['EC2_IAM_PROFILE_NAME'] %>

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04

suites:
- name: default
  run_list:
  - recipe[ahc-chef-server]
  attributes:
    ahc-chef-server:
      raid:
        delete_on_termination: true
        disk_size: 5
